# 2.a. 'pin' powershell to task bar -> not needed
- name: Step 2.a. 'pin' powershell to task bar
  ansible.builtin.meta: noop

#   b. setup winrm service -> use ansible: win_dsc
- name: Step 2.b. setup winrm service
  ansible.windows.win_dsc:
    resource_name: Service
    Name: WinRM
    StartupType: Automatic
    State: Running
